version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: pixel-game-db
    environment:
      POSTGRES_DB: pixelgame
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pixel-game-network

  # Go Backend Application
  backend:
    build: .
    container_name: pixel-game-backend
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres:password@postgres:5432/pixelgame?sslmode=disable
      GIN_MODE: release
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - pixel-game-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  pixel-game-network:
    driver: bridge
